version: "2"
linters:
  enable:
    - godot
    - revive
    - wsl_v5
  disable:
    - errcheck
    - unused
  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    wsl_v5:
      allow-first-in-block: true
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: survivor
      extra:
        group-params: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
